title: GitHub Page. Proyectos de temática libre que he realizado en mis cursos académicos.
author: Yannick Baratte Forner
email: yannickbf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Page de Yannick Baratte Forner para compartir los proyectos de temática libre de los cursos que he realizado ordenados de mas reciente a mas antiguo (Cert. Profesionalidad niv. 3 Desarrollo de aplicaciones con tecnología web y CFGS Desarrollo de aplicaciones web). 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  yannickbf # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-merlot
